"""Display event types for the event-sourced agent system.

This module defines events that represent display-related operations, such as
HTML rendering. These events track the display service's work in making agent
events visible to users.

Display events are generated by the display service when it renders events
into HTML or other display formats.
"""

# Event type constants for consistency
HTML_RENDERING_STARTED = "HTMLRenderingStarted"
HTML_RENDERING_COMPLETED = "HTMLRenderingCompleted"
